package config

// Config key constants — use these instead of string literals to get
// compile-time safety and a single place to update key names.
const (
	KeyModel      = "model"
	KeyEmbedModel = "embed_model"
	// KeyEmbedModelCode is the embedding model used exclusively by the learn
	// indexer for code chunks (indexed_files + indexed_chunks). When unset,
	// learn falls back to KeyEmbedModel. Keeping code embeddings in a
	// separate space lets Scot use a code-specialized model (e.g.
	// manutic/nomic-embed-code:7b-q8_0) without disturbing the prose space
	// used by memories, facts, and summaries.
	// When you change this key, run `cairo learn --reembed` on each indexed
	// project to rebuild code embeddings in the new space.
	KeyEmbedModelCode        = "embed_model_code"
	KeyOllamaURL             = "ollama_url"
	KeyAIName                = "ai_name"
	KeyMaxTurns              = "max_turns"
	KeySummaryModel          = "summary_model"
	KeySummaryThreshold      = "summary_threshold"       // unsummarized turns required (>) before summarizer fires
	KeySummaryBatchSize      = "summary_batch_size"      // user/assistant turns folded into one summary
	KeySummaryTokenThreshold = "summary_token_threshold" // estimated unsummarized token count (>) before summarizer fires
	KeyThink                 = "think"
	KeyThinkBudget           = "think_budget"
	KeyMemoryLimit           = "memory_limit"
	KeySummaryCtx            = "summary_context"
	KeyModelCtx              = "model_ctx"
	KeyLastDreamAt           = "last_dream_at"
	KeySearxNGURL            = "searxng_url"
	KeyUnsafeMode            = "unsafe_mode"
	KeyInitComplete          = "init_complete"
	KeyLastEmbedModel        = "last_embed_model"
	KeyKokoroURL             = "kokoro_url"            // e.g. "http://mac-studio-instruct:8880"
	KeyKokoroVoice           = "kokoro_voice"          // e.g. "af_sky"
	KeyToolOutputLimit       = "tool_output_limit"     // max bytes per tool result before truncation
	KeyUserName              = "user_name"             // how Selene addresses the human; set during /init
	KeyUserSteering          = "user_steering"         // user-owned directives, injected at top
	KeyUserContext           = "user_context"          // user-owned identity/preferences, after soul
	KeySynthesisNudge        = "synthesis_nudge_after" // tool-call threshold for the synthesis nudge; 0 disables
	KeyLLMAPIKey             = "llm_api_key"           // API key for OpenAI-compatible LLM backend

	// KeyGlamourStyle controls the glamour markdown renderer style.
	// Valid values: "dark" (default), "light", "notty", "auto".
	// "auto" triggers an OSC 11 terminal probe which may produce garbage
	// in some terminals — use "dark" or "light" for stability.
	KeyGlamourStyle = "glamour_style"

	// KeySessionFeedbackEnabled gates the end-of-session feedback loop.
	// When "true" (default), cairo asks the AI one closing question at the end
	// of a qualifying session and writes the answer as a feedback memory.
	KeySessionFeedbackEnabled = "session_feedback_enabled"

	// KeySessionFeedbackMinMessages is the minimum total message count required
	// before the feedback loop fires. Sessions below this threshold are
	// considered too short to yield durable feedback. Default: 6 (≈3 exchanges).
	KeySessionFeedbackMinMessages = "session_feedback_min_messages"

	// KeyLearnMaxChunkTokens caps the estimated token count for a single
	// indexed_chunk before the chunker splits it at a line boundary. Token
	// estimate: len(text)/4. Default: 400 (safety margin under nomic-embed-text's
	// 512-token window). Set lower to force finer splits; set higher at the risk
	// of silently truncating in the embed model.
	KeyLearnMaxChunkTokens = "learn_max_chunk_tokens"

	// KeyMemoryDedupThreshold is the cosine-similarity threshold above which
	// memory_tool.add() treats an incoming memory as a near-duplicate and
	// returns a warning instead of writing. Range: 0–1; default "0.85".
	// Set to "1.0" to effectively disable dedup (only exact-vector matches blocked).
	KeyMemoryDedupThreshold = "memory_dedup_threshold"

	// KeyJobMaxReviewIterations caps how many times the orchestrator's
	// coder→reviewer cycle may repeat per plan step. When the cap is
	// reached the orchestrator is expected to surface BLOCKED rather than
	// retrying indefinitely. Default 3.
	KeyJobMaxReviewIterations = "job_max_review_iterations"

	// KeyServerToken is the bearer token used when the server is started
	// with --auth. Generated by GenerateToken() and stored for reuse across
	// restarts. Not set by default; empty string means no token is stored.
	KeyServerToken = "server_token"

	// KeyServerPort is the default TCP port for cairo serve. Can be
	// overridden at startup with --port. Default: 1337.
	KeyServerPort = "server_port"

	// Consider (inner-dialogue) config keys.
	// KeyConsiderEnabled gates the pre-turn inner-dialogue step. Default "false".
	KeyConsiderEnabled = "consider.enabled"
	// KeyConsiderModel is the model used for each aspect call. Default "qwen3.5:2b-mlx-bf16".
	KeyConsiderModel = "consider.model"
	// KeyConsiderSummaryModel is the model used for the summarizer call. Defaults to KeyConsiderModel.
	KeyConsiderSummaryModel = "consider.summary_model"
	// KeyConsiderTemplate is the user-editable prompt template for aspect calls.
	// Supports {name} and {traits} substitutions.
	KeyConsiderTemplate = "consider.template"
	// KeyConsiderIncludeUserHistory controls whether the last 3 user messages
	// (prior to the current one) are prepended as context to each aspect call.
	// Default ON — only "false" disables. Conversation history (user-only, no
	// soul or assistant messages) gives aspects conversational footing without
	// the identity-contamination that prompted the original full strip.
	KeyConsiderIncludeUserHistory = "consider.include_user_history"

	// KeyPendingSessionID is a one-shot queue for the session to resume on
	// next launch. Set by the Ctrl+B sessions panel when the user presses
	// Enter on a session; cleared immediately by resolveSession on read so
	// the pick is consumed and never replayed.
	KeyPendingSessionID = "pending_session_id"

	// KeyRegistryURL is the base URL of the cairo-registry service.
	// When set, cairo registers on startup, runs a heartbeat loop, and holds
	// a WebSocket liveness stream. Empty means registry integration is disabled.
	KeyRegistryURL = "registry_url"

	// KeyRegistryHeartbeatInterval is the re-registration interval in seconds.
	// Default 60 when not set or invalid.
	KeyRegistryHeartbeatInterval = "registry_heartbeat_interval"

	// KeyRegistryAgentID is the stable agent UUID assigned by cairo-registry.
	// Persisted after first registration so the same row is updated on
	// subsequent registrations, even across hostname changes.
	KeyRegistryAgentID = "registry_agent_id"

	// KeyDreamCuratorSimilarityThreshold is the cosine-similarity threshold
	// above which two unreviewed memories (or facts) sharing the same embed
	// model are considered near-duplicates by the dream-pass curator. The
	// loser is soft-archived and hard-deleted on the next cycle. Range: 0–1;
	// default "0.92". Raise to be more conservative; lower to merge more
	// aggressively.
	KeyDreamCuratorSimilarityThreshold = "dream_curator_similarity_threshold"
)
